---
- name: uninstall and install httpd software
  hosts: executable
  
  tasks:
  - name: Remove httpd
    yum: pkg=httpd state=absent
    
  - name: Install httpd
    yum: pkg=httpd state=present
    
